### PR TITLE
use trusty instead of precise (travis)

### PR DESCRIPTION
**Pull request by pat-s**
see #114 and https://github.com/mlr-org/mlr/pull/1912#issuecomment-317062603

### CODE REVIEW

**Comment by pat-s** [comment]
@larskotthoff ready for merge?

**Comment by berndbischl** [comment]
is the "a" here a typo?

 - git config credential.helper "store --file=.git/credentials"a

**Comment by larskotthoff** [comment]
Why do we need sudo here? Why not install the packages like in the main repo?

**Comment by pat-s** [comment]
> Why do we need sudo here? Why not install the packages like in the main repo?

There was a misunderstanding on my side with the whitelisted packages. Nevermind. Changed :)

> is the "a" here a typo?

yes

**Comment by berndbischl** [comment]
ok lets merge when travis is finished and green

**Comment by SteveBronder** [comment]
Should we update this now that mlr's travis is up and running?

**Comment by pat-s** [comment]
> Should we update this now that mlr's travis is up and running?

Yes, adapt it to mlr travis. I had not time in the last days, I'll try to update it asap

**Comment by larskotthoff** [comment]
We're currently timing out. Can we have build stages here as well?

**Comment by berndbischl** [comment]
would be great if we could resolve this, yes. this is blocking us

**Comment by pat-s** [comment]
I tried to split up the knitting by stages but it seems that resulting .md files are not carried over to the next stage? see [this build](https://travis-ci.org/mlr-org/mlr-tutorial/builds/264686877?utm_source=github_status&utm_medium=notification)
building everything in one stage leads to [timeout](https://travis-ci.org/mlr-org/mlr-tutorial/builds/264711235).

@mllg any ideas?

**Comment by SteveBronder** [comment]
Would we be able to break it up into multiple chunks of .md files to be tested?

**Comment by pat-s** [comment]
> Would we be able to break it up into multiple chunks of .md files to be tested?

@SteveBronder thats what I tried (if I understand you correctly)

**Comment by pat-s** [comment]
As we have working builds on trusty, I close this here.

**Pull request closed without merging**
