### PR TITLE
update to partial_prediction

### PR DESCRIPTION
**Pull request by zmjones**
- no redundancy in expensive function calls
- section about bounds in plots
- clearer exposition at top

second commit is an update for `plotFilterValuesGGVIS`, which doesn't have the argument that is mentioned and does a few new things.

### CODE REVIEW

**Comment by zmjones** [comment]
this was an over 50 minutes error. i also noticed that the `custerSim` package bug shows up in the logs.

**Comment by larskotthoff** [comment]
I've restarted it. The `clusterSim` thing is caused by the maximum number of DLLs that can be loaded into R and unrelated to the package itself or any of your changes.

**Comment by zmjones** [comment]
ok cool, thanks

**Comment by larskotthoff** [comment]
Ok, that almost finished -- merging.

**Pull request merged**
