### PR TITLE
New logos - for folder "img" and "custom_theme/img"

### PR DESCRIPTION
**Pull request by juliabrosig**

### CODE REVIEW

**Comment by jakob-r** [comment]
Looks pretty bad here:
tutorial screen shot

**Comment by jakob-r** [comment]
For the blog I can set the change: However it looks a bit strange, as we know have the term mlr 3 times nearly in the same typo.

image

**Comment by mb706** [comment]
Maybe color the little bricks white in `mlr_white.png` (or also use a background there)

Also, why not change "mlr: Machine Learning for R."  to just "Machine Learning for R." when the logo is shown next to it and remove the "mlr-org" text entirely.

**Comment by juliabrosig** [comment]
regarding the tutorial - do you think it looks better if the mlr = white and the squares = grey? or maybe it also looks quite boring then. But then we would have to change the background color of the tutorial ...

**Comment by mb706** [comment]
This is #b0c4de for the blocks:
mlrx

**Comment by pat-s** [comment]
Maybe we could focus the efforts on implementing the new logo in the [pkgdown approach](https://pat-s.github.io/mlr/index.html)?
I am just working on replacing the `mlr` text that links to the site index with the logo.
Everyone should have the rights to add commits to my [PR](https://github.com/mlr-org/mlr/pull/2123).

See the following line for the logo implementation in the navbar: 

https://github.com/pat-s/pkgdown/blob/cc1579abcf00cb11bc856e48f3b9d3c91432c2c2/inst/templates/navbar.html#L10

**Comment by jakob-r** [comment]
Sounds reasonable.

**Comment by jakob-r** [comment]
So I guess this issue can be closed @pat-s ?

**Comment by pat-s** [comment]
Yes. We should clean up here. I can't ;)

**Pull request closed without merging**
