### PR TITLE
Fix travis issue

### PR DESCRIPTION
**Pull request by pat-s**
Introduced by https://github.com/mlr-org/mlr/commit/f947f414438cfb3bfe992c3634d4529de566ff6b

### CODE REVIEW

**Comment by larskotthoff** [comment]
What's the problem here? As far as I can see the commit that you've linked to has nothing to do with the fix.

**Comment by pat-s** [comment]
Ah sorry, meant this commit: https://github.com/mlr-org/mlr/commit/455f3e275e56f697c7cd26385e06c339ba5df743

The commit introduced a name change in `sonar.task` and `iris.task` changing a `-` to a `_` which causes the build to fail. See last `gh-pages` builds of `mlr-tutorial`, e.g. https://travis-ci.org/mlr-org/mlr-tutorial/builds/313653705

The builds of this PR run fine but error due to timeout.

**Comment by jakob-r** [comment]
Hopefully travis can turn green within the time limit. Then it can be merged.

**Comment by jakob-r** [comment]
`Knitting file 'partial_dependence.Rmd' ...` took longer than 10mins?

**Comment by pat-s** [comment]
> Knitting file 'partial_dependence.Rmd' ... took longer than 10mins?

I also do not know what causes this. Travis trusty update, mlr update, mlr-tutorial update?

**Comment by jakob-r** [comment]
Well. I don't care at the moment. The important part was fixed and was knitted without errors.

**Pull request merged**
