### PR TITLE
updates partial prediction tutorial

### PR DESCRIPTION
**Pull request by zmjones**
- adds partial derivative plots
- adds predict.type = "se" plots

### CODE REVIEW

**Comment by schiffner** [comment]
Thank you very much.

nitpicking :) :
l. 17: ensemebles
first paragraph in usage: Could you please link to the documentation of class `PartialPredictionData`?

**Comment by zmjones** [comment]
fixed, thanks!

**Comment by schiffner** [comment]
Thanks.
Really sorry to bother you again, but `PartialPredictionData` must be capitalized.

**Comment by zmjones** [comment]
Fixed, although the link isn't going to work as rdocumentation still is on 2.2!

**Comment by schiffner** [comment]
I know. That's really annoying.

**Comment by zmjones** [comment]
50 min timeout. it hadn't even gotten past nested resampling. any idea what has changed since the last time it was built? maybe it was just a change in the download time for the packages?

**Comment by schiffner** [comment]
Mmmh... It was pretty close. As far as I can see the Travis build died while knitting wrapper.Rmd.
I compared to the latest successful build (41min) and the download/installation times were a little larger this time, but do not explain 9 min. I'm not sure what changed.
Will merge for now and see what happens. :)

**Comment by zmjones** [comment]
The time on my part definitely did go up as the numerical differentiation is not the fastest. Fingers crossed though!

**Comment by schiffner** [comment]
The finger crossing helped. :) The logs show that the knitting time definitely went up, but there are some other examples in the tutorial that I wanted to shorten anyway.

If you are also wondering why there are no changes in the online tutorial: I just found out that there is an error in pushing the html pages to /devel. Not yet sure what is happening there...

**Pull request merged**
