### PR TITLE
WIP - cleanup basic section of tutorial

### PR DESCRIPTION
**Pull request by masongallo**
As we discussed long ago, I am cleaning up the tutorial:

- cleaning up english / grammar
- moved preprocessing to basic section since it's a crucial step on real world data
- changed basic name to quick walkthrough so user can follow along to quickly get acquainted with mlr capabilities

### CODE REVIEW

**Comment by jakob-r** [comment]
Thanks a lot for the work so far. Let us know whenever you want specific feedback.

**Comment by masongallo** [comment]
Closing this, I will do in smaller chunks at a time so it's realistic for me to finish

**Comment by jakob-r** [comment]
Before you delete the branch let someone of us go through your proposed changes before all work is lost.

**Comment by jakob-r** [comment]
Although this is marked as WIP I don't see any drawback in merging it now. Thoughts?

**Comment by berndbischl** [comment]
read over it, merge it then

**Comment by jakob-r** [comment]
All corrections are improving the text enormously.

**Pull request merged**
