### PR TITLE
adds classifier calibration plot page

### PR DESCRIPTION
**Pull request by zmjones**

### CODE REVIEW

**Comment by zmjones** [comment]
looks like the build failed installing paramhelpers. can someone restart the build?

**Comment by larskotthoff** [comment]
Restarted.

**Comment by larskotthoff** [comment]
Argh, looks like we need to call `.build` _four_ times now for everything to load. @zmjones I can do that in master, but it's probably easier if you change that here.

**Comment by zmjones** [comment]
I am confused. I should just add another `.build` under `script`? Why does it need to be called multiple times?

**Comment by larskotthoff** [comment]
In `.travis.yml`, replace

```
- ./build || ./build || ./build
```

with 

```
- ./build || ./build || ./build || ./build
```

We unfortunately need this because of the DLL limit in R -- the packages it's complaining about are actually installed, they just can't be loaded. Rerunning `./build` will cause it to take the cached output for files that have been finished before and not load those packages.

**Comment by zmjones** [comment]
Ah ok, done.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
