### PR TITLE
update 'handling of spatial data' with updated approach in mlr

### PR DESCRIPTION
**Pull request by pat-s**
https://github.com/mlr-org/mlr/commit/2ebd2f29bb8adcf5f865ca3a6b579c71ca96c072

### CODE REVIEW

**Comment by pat-s** [comment]
@jakob-r @larskotthoff this is blocking the build. See https://travis-ci.org/mlr-org/mlr-tutorial/builds/334603804.

Can we merge this? Should be merged together with https://github.com/mlr-org/mlr-tutorial/pull/140 as both #140 and #139  will only pass if the other is merged, too.

**Comment by larskotthoff** [comment]
Hmm, could you make one PR for both in this case? I'd like to see the build pass before merging.

**Comment by pat-s** [comment]
I assume it will still fail because of https://github.com/mlr-org/mlr-tutorial/issues/141

Edit: As expected

**Comment by zmjones** [comment]
ok this passes locally for me using the master version of mlr. is it possible that an older version is being loaded?

**Comment by zmjones** [comment]
i found the bug and am working on it now. will have to issue a pr in mlr and then it should work.

**Comment by jakob-r** [comment]
Why is the logo part of this PR? Can you merge in master pls?

**Comment by pat-s** [comment]
Oh no it auto merged all the devel/ files again..
Cleaning up later. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pat-s** [comment]
@jakob-r @larskotthoff ready to merge

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
