### PR TITLE
Added tutorial for multilabel classification

### PR DESCRIPTION
**Pull request by PhilippPro**
- added a multilabel section where the construction and application of a multilabel learner is explained
- added multilabel task and a multilabel classification section to task.rmd
- added a multilabel learner (rFerns) in learner.rmd
- added a description in createLearner.rmd on how to create an (algorithm adaption) multilabel learner

### CODE REVIEW

**Comment by schiffner** [comment]
Thank you very much! Looks good!

I read quickly over everything. Here are some comments (mainly regarding formatting):
- I`m pretty sure it must be "algorithm adaptation" not "adaption".
- I noticed that many code chunks in the multilabel section don't show any output. For example it would be nice if you could print the `yeast.task` in l. 25 or the `multilabel.lrn` in l.48-50 or the result of resampling in l.109, you get my drift...
- Could you please make sure that there is a blank line between outputs (for example between `mod` and `mod2` in l. 71-72 in `multilabel.Rmd`)?

And it would be nice if you could make some quick changes to three other tutorial sections:
- Could you add a link to the multilabel stuff in the beginning of `wrapper.Rmd`?
- Could you also have a look at `integrated_learners.Rmd` and add a table for the multilabel learners? As you will see there is a script based on `listLearner` that builds the tables automatically. You basically have to add a new paragraph for multilabel and check if the auto-generated table is ok.
- And could you do the same to `measures.Rmd`?

**Comment by PhilippPro** [comment]
Ok, thanks for the annotations, I fixed and added the commented things. First thought, that it looks a bit ridiculous to have only one learner and one measure in the integrated sections in the appendix, but I think it looks ok and probably it will be expanded. 

One thing I noticed is, that the font size differs in the implemented performance and integrated learner sections, e.g. the cost sensitive performance measures are much bigger (and the multilabel things, too).

**Comment by berndbischl** [comment]
dont worry about the one learner only. this is ok and we cannot magically improve that number. 

just make sure that in the normal multilabel page the brwrapper is explained. that gives us a dozen methods.

**Comment by schiffner** [comment]
@IcedragonP : Thanks for the changes, looks good.
The Travis fail is not related to something you did, but to changes in mlr.
So, I will merge, try to fix Travis and then iterate over the multilabel stuff.

About the low number of measures/learners for multilabel: What Bernd said...

**Comment by schiffner** [comment]
> One thing I noticed is, that the font size differs in the implemented performance and integrated learner sections, e.g. the cost sensitive performance measures are much bigger (and the multilabel things, too).

Sorry, forgot to answer that. That's intended to better fit the wider tables on standard screens.

**Pull request merged**
