### PR TITLE
Extended critDifferences interpretation, fix typos

### PR DESCRIPTION
**Pull request by pfistfl**
Updated to include Information on interpretation and calculation of critical differences plot.
Please iterate over it so I can fix / improve stuff.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, but you're introducing quite a number of typos -- missclassification should be misclassification, neccessary should be necessary, etc. Please run a spell checker.

**Comment by schiffner** [comment]
Also, please leave `[Learner](&makeLearner)` capitalized.

**Comment by pfistfl** [comment]
Done, anything else?

**Comment by schiffner** [comment]
I went over the diffs and spotted some minor stuff. Could you please correct?

l. 171: By evaluating at the result...

l. 220: Many researchers feel the need to display an algorithms superiority ...
-> algorithm's

l. 222: Function `friedman. test` is in package `stats`, not `base`.
Can you please correct the links and the text that says that it's in package `base`?

l. 246: differ by more then the critical differences
-> than

l. 247: then -> than

l. ~271: Instead of just comparing mean performance values It is generally preferable -> it

**Comment by pfistfl** [comment]
done, I did not see those errors. Rather embarrassing.

**Comment by schiffner** [comment]
Thanks very much!
And no worries! It's always much harder to find your own errors... :)

Going to merge.

**Pull request merged**
