### PR TITLE
Conf matrix and ROCMeasures

### PR DESCRIPTION
**Pull request by ja-thomas**
Documentation for two new functions in mlr `calculateROCMeasures` and `calculateConfusionMatrix`.

Do not merge this before PR [#1113](https://github.com/mlr-org/mlr/pull/1113) and [#1071](https://github.com/mlr-org/mlr/pull/1071) in mlr are merged.

Feedback appreciated :)

### CODE REVIEW

**Comment by ja-thomas** [comment]
Both above mentioned PRs are now merged. Should hopefully be ready to merge after travis passes and somebody has proofread it.

Thanks

**Comment by schiffner** [comment]
Will do, thx!

**Comment by schiffner** [comment]
Sorry for taking this long and thank you for writing this!

I went into your branch, did a little cleanup and tweaked the language a little.
The only small addition I made is to show how to get the relative values normalized in one direction from the `ConfusionMatrix` object (i.e. `$relative.col` and `$relative.row`, because that's something that I would want to know and use).
Ok?

The link from the performance page to the confusion matrix section was broken. How to do this correctly is not explained very clearly in the mkdocs documentation. I added a short explanation to the tutorial README, so in the future we know...

**Comment by ja-thomas** [comment]
perfect, thanks :)

**Comment by schiffner** [comment]
Ok, merging. And also thanks :)

**Pull request merged**
