### PR TITLE
Cheatsheet

### PR DESCRIPTION
**Pull request by Prometheus77**
I've created a new mlr cheatsheet that I'd like to upload for feedback / comments.
[MlrCheatsheet_AC_v0.5.pdf](https://github.com/mlr-org/mlr-tutorial/files/1178331/MlrCheatsheet_AC_v0.5.pdf)
[MlrCheatsheet_AC_v0.5.pptx](https://github.com/mlr-org/mlr-tutorial/files/1178333/MlrCheatsheet_AC_v0.5.pptx)

BB: here is the google doc with remaining todos
https://docs.google.com/document/d/1ypuVm-bmvBCGSN1FH8RyuRajJaR3luBOes1y3neP0yw/edit

### CODE REVIEW

**Comment by berndbischl** [comment]
1) ugh, wtf :) that looks great.
@mllg and @jakob-r are also working on a cheatsheet and think this is really important. 
our stuff is here: 
https://docs.google.com/presentation/d/1amJt_mpCus9C0jvcoKm1L9SaGZ889yF84djab6fK4l0/edit?usp=sharing

it is much easier to maintain this as a google doc

2) 
we should *really* talk and join these 2. you dont have by any change time on friday 13-18? (german time)? because we are meeting then to work on this.

3) why is this in a PR with 600 changed files?

**Comment by Prometheus77** [comment]
1. I'm well-versed in PPTX; not nearly as good with Google docs. If someone who has that expertise would like to try to convert it over, that would be fine, but my guess is that will break a lot of things. I think the better route is for the community to provide feedback, and me to make changes in PPTX and re-upload. Ultimately the final version will be published as .PDF, right?
2. I am on MST (-0700), I believe that will be 05:00-10:00 my time. I can be available for probably the first half of that. PM me a meeting link and I'll hop on.
3. Because I don't really have experience with git. I just went to the Cheatsheet page, clicked "Create pull request", and that's what happened. I'll try to figure out how to resubmit properly.

**Comment by berndbischl** [comment]
we are online now, under google hangout.
do you want to join?

**Comment by jakob-r** [comment]
I fixed the base to `gh-pages`. PR looks _technically_ okay now.

**Comment by Prometheus77** [comment]
I'm available to join the session. My gmail address is aaronsama@gmail.com

**Comment by berndbischl** [comment]
hi. @Prometheus77 
we had noted all of our comments in the google doc.
will you iterate?

**Comment by Prometheus77** [comment]
Yes, thank you for your valuable feedback. I've been making improvements
the past few days and hope to post an updated version soon. BTW, I enjoyed
meeting the team!

Aaron

**Comment by berndbischl** [comment]
> Yes, thank you for your valuable feedback.

you certainly dont have to thank *us* :)
it is quite the opposite :)

**Comment by berndbischl** [comment]
i added the gdoc to the 1st post

**Comment by Prometheus77** [comment]
Going to close this pull request and create another one.

**Comment by Prometheus77** [comment]
Okay, so I'm having trouble pulling and pushing, probably a combination of access rights and not really being experienced with Github. I've made a number of updates to the version of the cheatsheet we discussed a few weeks back. I think it covers everything, but have labelled it v0.9 because I expect we're not quite there yet.

I'll have uploaded the files in this comment, and someone with the right combination of access and knowledge I lack can merge them in.

[MlrCheatsheet_v0.9.pdf](https://github.com/mlr-org/mlr-tutorial/files/1227039/MlrCheatsheet_v0.9.pdf)
[MlrCheatsheet_v0.9.pptx](https://github.com/mlr-org/mlr-tutorial/files/1227038/MlrCheatsheet_v0.9.pptx)

**Comment by berndbischl** [comment]
> Okay, so I'm having trouble pulling and pushing, probably a combination of access rights and not really being experienced with Github.

do you have a specific question? how can we help?

did you make some notes in the google doc what  you worked on / is done, so i can easier check the new version?

**Comment by Prometheus77** [comment]
So I pulled the "cheatsheet" branch on to my local machine using Github
Desktop. Then I dropped the new .pptx and .pdf files into
mlr-tutorial/cheatsheet and tried to "push origin", only to get the
message: Authentication failed. You may not have permission to access the
repository. Open options and verify that you're signed in with an account
that has permission to access this repository.

I'll make detailed updates to the Google doc shortly.

**Comment by Prometheus77** [comment]
...and new versions:
[MlrCheatsheet_v0.95.pdf](https://github.com/mlr-org/mlr-tutorial/files/1229758/MlrCheatsheet_v0.95.pdf)
[MlrCheatsheet_v0.95.pptx](https://github.com/mlr-org/mlr-tutorial/files/1229757/MlrCheatsheet_v0.95.pptx)

**Comment by Prometheus77** [comment]
Just checking in to see if you've had a chance to review the updated cheatsheet I uploaded a few weeks back and had any further suggestions or wanted to discuss.

**Comment by jakob-r** [comment]
Thanks. It looks really comprehensive! Maybe we should schedule another hangout. Until then we @berndbischl @mllg should have read it carefully and probably can give it a go.

**Comment by Prometheus77** [comment]
Let me know if / when you have availability and we can get on another call to finalize. I'm going to teach an mlr class to my company's data science organization at the beginning of November: would be great to have the cheatsheet published by then.

**Comment by Coorsaa** [comment]
Really nice cheatsheet!!
In the **Introduction** box I would simplify *"how the learner is to obtain the performance measure"* to *"how the learner obtains the..."* or *"how the learner evaluates the..."*.

**Comment by lbeggel** [comment]
Hi, looks great! Would have never thought that the whole mlr can fit on 2 pages ;)
Some small comments:
Setup: summarizeColumns misses '.' after '... or task'
makeCostSensTask: i would change it to ' ... each observation-cost pair ...'
Training& Testing: the second description in getParamSet sounds hard to understand
Refining Performance: i would add '.'  after '..., trafo = function(x) . ' and afte r' ...exponentially .'
Quickstart: in Create and train learner, the 'test performance' sounds misleading. Maybe change it to 'evaluate' or something similar?
Feauture filtering: in the first figure, the vertical dashed line starts with a fourth dash but which is cut off. Looks like a smear.  And it's crooked :) Additionally, on screen, the red boxes in the figures tend to look too bulky. Suggestion would be to use a thinner linestyle.
Wrappers: is this a coincidence that makePreprocWrapper and makePreprocWrapperCaret are black and not blue?

**Comment by juliabrosig** [comment]
Hi, it looks really good. Some design remarks are added in the Google doc https://docs.google.com/document/d/1ypuVm-bmvBCGSN1FH8RyuRajJaR3luBOes1y3neP0yw/edit

**Comment by Prometheus77** [comment]
I incorporated Stefan's, lbeggel's, and Julia's suggestions and made a few
additional improvements.

I requested permission to the Google Doc with the new logo; once I am able
to add the logo, I'll commit the final cheatsheets to the branch and send a
pull request.

-Aaorn

**Comment by juliabrosig** [comment]
@Prometheus77 
where exactly did you upload the cheatsheet?
I can't find it.
Thanks!

**Comment by Prometheus77** [comment]
Tried to push to origin just now (mlr-tutorial, branch "cheatsheet"), but
got:
Authentication failed. You may not have permission to access the
repository. Open options and verify that you're signed in with an account
that has permission to access this repository.

**Comment by juliabrosig** [comment]
ok now you should have access! 
Please try to upload it again.
Thank you

**Comment by larskotthoff** [comment]
Looks good -- one suggestion: Could the quotes in the example commands be normal quotes (") instead of the fancy start-end quotes? Then you could copy and run the commands directly.

**Comment by Prometheus77** [comment]
Still not able to (getting same message about authentication). I'm dragging and dropping into this comment instead. If someone with proper access can commit and merge them, I'd be much obliged!
[MlrCheatsheet_v1.0.pdf](https://github.com/mlr-org/mlr-tutorial/files/1540989/MlrCheatsheet_v1.0.pdf)
[MlrCheatsheet_v1.0.pptx](https://github.com/mlr-org/mlr-tutorial/files/1540990/MlrCheatsheet_v1.0.pptx)

**Comment by jakob-r** [comment]
It looks awesome. I updated it directly to the master. Thanks again.

**Pull request merged**
