### PR TITLE
added more multilabel learners and measures

### PR DESCRIPTION
**Pull request by PhilippPro**

### CODE REVIEW

**Comment by schiffner** [comment]
Very cool. Thanks. 
I can go over this tomorrow.

**Comment by PhilippPro** [comment]
There are two code lines still commented, as the multilabel PR is still not merged

**Comment by schiffner** [comment]
There was a small problem with the measures table, therefore Travis failed. That's fixed now, so hopefully the tutorial will build as soon as the multilabel random forest is merged.

Some measure names still have to be updated, but I guess you know this already.

**Comment by PhilippPro** [comment]
Can you restart the travis build, pls? The multilabel-randomForestSRC pr is now merged...

**Comment by berndbischl** [comment]
> Can you restart the travis build, pls? The multilabel-randomForestSRC pr is now merged...

done. you still might have to rebase on master here. pls check that

**Comment by berndbischl** [comment]
new PR is #45

**Pull request closed without merging**
